# Generated by Django 3.2.4 on 2021-07-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoP', models.CharField(max_length=30)),
                ('apellidoM', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=80)),
            ],
        ),
    ]
